[create_shortcut]
name = "创建 $ 快捷方式"
step = "Link"
source_file = "Code.exe"
target_name = "Visual Studio Code"

[copy]
step = "Copy"
from = "${Desktop}/*"
to = "./"

[add_path]
step = "Path"
record = "114.exe"
operation = "Add"