[workspace]
resolver = "2"
members = [
    "crates/ept-lib",
    "crates/ept-cli",
]

[workspace.package]
version = "0.4.3"
edition = "2021"
authors = ["Cno"]
license = "MIT"
repository = "https://github.com/EdgelessPE/ept"

[workspace.dependencies]
# 内部 crate
ept-lib = { path = "crates/ept-lib" }

# 基础依赖
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
toml = { version = "1.0.1", features = ["preserve_order"] }

[profile.release]
lto = true