[package]
name = "ept"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
base64 = "0.21.0"
blake3 = { version = "1.3.3", features = ["rayon"] }
clap = { version = "4.1.4", features = ["derive"] }
colored = "2.0.0"
console = "0.15.5"
dirs = "4.0.0"
envmnt = "0.10.4"
eval = "0.4.3"
lazy_static = "1.4.0"
memmap2 = "0.5.8"
mslnk = "0.1.8"
openssl = "0.10.45"
regex = "1.7.1"
rustyline = "10.1.1"
semver = "1.0.16"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tar = "0.4.38"
toml = { version = "0.5.11", features = ["preserve_order"] }
winreg = "0.10.1"
zstd = "0.12.3"
