[toast]
name = "Toast"
step = "Toast"
if = "ExitCode==0"
title = "Updated successfully"
content = "Code has been installed"

[toast_else]
name = "Toast else"
step = "Toast"
if = "ExitCode!=0"
title = "Updated failed"
content = "Uninstall code then try again"

[add_path]
name = "Add Dir PATH"
step = "Path"
record = "bin"
operation = "Add"

[updater]
name = "Run updater"
step = "Execute"
command = "updater.exe /S"
call_installer = true