[setup_flow.create_shortcut]
name = "Create shortcut"
type = "Link"
source_file = "./VSCode/VSCode.exe"
target_name = "Visual Studio Code"

[setup_flow.add_path]
name = "Add PATH"
type = "Path"
record = "./VSCode"
operation = "Add"

[setup_flow.log_status]
name = "Log status"
type = "Log"
level = "Info"
msg = "VSCode installed successfully"