// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Package } from "./Package";
import type { Software } from "./Software";

export type GlobalPackage = {
	nep: string;
	package: Package;
	software: Software | null;
};
