// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalPackage } from "./GlobalPackage";
import type { Permission } from "./Permission";

export type MetaResult = {
	temp_dir: string | null;
	permissions: Array<Permission>;
	workflows: Array<string>;
	package: GlobalPackage;
};
