// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionKey } from "./PermissionKey";
import type { PermissionLevel } from "./PermissionLevel";

export type Permission = {
	key: PermissionKey;
	level: PermissionLevel;
	targets: Array<string>;
};
