// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PermissionKey =
	| "path_entrances"
	| "path_dirs"
	| "link_desktop"
	| "link_startmenu"
	| "execute_installer"
	| "execute_custom"
	| "fs_read"
	| "fs_write"
	| "download_file"
	| "process_query"
	| "nep_installed"
	| "notify_toast"
	| "process_kill";
