[create_shortcut]
name = "Create shortcut"
step = "Link"
source_file = "Code.exe"
target_name = "Visual Studio Code"

[add_path]
name = "Add PATH"
step = "Path"
if   =  "${AppData} if = 114514"
record = "Code.exe"
operation = "Add"

[wait]
name = "Wait"
step = "Wait"
timeout = 30000
break_if = "true"