name: Build release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run build
        run: npm run rs:build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/ept.exe
