name: Build release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install git cliff
        run: cargo install git-cliff

      - uses: Swatinem/rust-cache@v2

      - uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: npm i pnpm@9 --global && pnpm install

      - name: Run build
        run: npm run rs:release

      - name: Generate a changelog
        run: git cliff -s all --current -o CURRENT_CHANGELOG.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CURRENT_CHANGELOG.md
          files: target/release/ept.exe
