name: Build release

on: 
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run build
        run: npm run rs:build
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: target/release/ept.exe
