name: Run unit test

on: 
  push:
    paths:
      - "src/**"
      - "examples/**"
  pull_request:
    paths:
      - "src/**"
      - "examples/**"
    

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2.6.2
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test -- --test-threads 1
