name: Run unit test

on: 
  push:
    paths:
      - "src/**"
      - "examples/**"
  pull_request:
    paths:
      - "src/**"
      - "examples/**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with: 
          components: cargo-tarpaulin
      - uses: Swatinem/rust-cache@v2.6.2
      - name: Build
        run: cargo build
      - name: Run tests
        run: npm run rust:ut:xml
      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: cobertura.xml
