name: Deploy Wiki

on:
  push:
    branches: [develop]
    paths:
      - "doc/**"
      - ".github/workflows/wiki.yml"
      - "./package.json"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  serve:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 获取仓库源码
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ github.ref }}

      # 缓存依赖
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      # 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 构建 Wiki
      - name: Run scripts
        run: pnpm build

      # 部署 Wiki
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './doc_build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
